### ISSUE TITLE
add_widget compile html

### ISSUE THREAD

**Issue by LTN** [tmrudick/angular-gridster#10]
Hi! Thank u! Is very fine directive! 
How compile added widget?

My code:

.directive('createWidget', function() {
    return {
        require: '^gridster',
        link: function(scope, element, attr, controller) {				
		element.on('click', function() {
			controller.gridster()
.add_widget( '<li ng-repeat="grid in items">{{item}}</li>',  2, 1);
		});
        }
    };
});

ng-repeat="grid in items" is not worked. :( 
Please help me

**Comment by tmrudick** [comment]
Hello! I no longer maintain this project, you might want to check out https://github.com/ManifestWebDesign/angular-gridster instead.
